parseArger update

diff --git a/bin/add b/bin/add
--- a/bin/add
+++ b/bin/add
@@ -15,12 +15,16 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger flag force "force overwrite if server exists" --short f
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -49,7 +53,10 @@ _arg_force="off"
 
 print_help()
 {
-	echo -e "add a server:"
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "add a server:"
 	echo -e "	name: server name"
 	echo -e "	ip: ip address"
 	echo -e "	user: username"
@@ -59,7 +66,9 @@ print_help()
 	echo -e "	--port <port>: ssh port [default: ' 22 ']"
 	echo -e "	-f|--force|--no-force: force overwrite if server exists"
 	echo -e "Usage :
-	$0 <name> <ip> <user> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--[no-]force]"
+	$0 <name> <ip> <user> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--[no-]force]";
+	fi
+
 }
 
 parse_commandline()
@@ -113,9 +122,11 @@ parse_commandline()
 				_arg_port="${_key##--port=}"
 				;;
 			
-			-f|--no-force|--force)
+			-f|--force)
 				_arg_force="on"
-				test "${1:0:5}" = "--no-" && _arg_force="off"
+				;;
+			--no-force)
+				_arg_force="off"
 				;;
 			-h|--help)
 				print_help;
@@ -123,6 +134,14 @@ parse_commandline()
 				;;
 			-h*)
 				print_help;
+				exit 0;
+				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
 				exit 0;
 				;;
 			*)
@@ -139,8 +158,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name ip user"
-	test "${_positionals_count}" -le 3 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 3 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 3 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 3 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 3 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 3 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 3 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 3 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -152,7 +176,7 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -166,17 +190,28 @@ print_debug()
 	echo -e "\tname: ${_arg_name}";
 	echo -e "\tip: ${_arg_ip}";
 	echo -e "\tuser: ${_arg_user}";
-	echo -e "\tpassword: ${_arg_password | sed 's/-/_/g'}";
-	echo -e "\tkey: ${_arg_key | sed 's/-/_/g'}";
-	echo -e "\tauth: ${_arg_auth | sed 's/-/_/g'}";
-	echo -e "\tport: ${_arg_port | sed 's/-/_/g'}";
-	echo -e "\tforce: ${_arg_force | sed 's/-/_/g'}";
+	echo -e "\tpassword: ${_arg_password}";
+	echo -e "\tkey: ${_arg_key}";
+	echo -e "\tauth: ${_arg_auth}";
+	echo -e "\tport: ${_arg_port}";
+	echo -e "\tforce: ${_arg_force}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/bin/connect b/bin/connect
--- a/bin/connect
+++ b/bin/connect
@@ -11,12 +11,16 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger opt exec-before "commands to execute before the shell" --repeat
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -41,12 +45,17 @@ _arg_leftovers=()
 
 print_help()
 {
-	echo -e "connect to a server:"
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "connect to a server:"
 	echo -e "	name: server name"
 	echo -e "	--cd <cd>: cd to directory"
 	echo -e "	--exec-before <exec-before>: commands to execute before the shell, repeatable"
 	echo -e "Usage :
-	$0 <name> [--cd <value>] [--exec-before <value>]"
+	$0 <name> [--cd <value>] [--exec-before <value>]";
+	fi
+
 }
 
 parse_commandline()
@@ -82,6 +91,14 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -96,7 +113,10 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -115,7 +135,7 @@ assign_positional_args()
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
 			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -127,15 +147,26 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tcd: ${_arg_cd | sed 's/-/_/g'}";
-	echo -e "\texec-before: ${_arg_exec-before | sed 's/-/_/g'}";
+	echo -e "\tcd: ${_arg_cd}";
+	echo -e "\texec-before: ${_arg_exec_before[*]}";
 	echo -e "\tleftovers: ${_arg_leftovers[*]}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/bin/cp b/bin/cp
--- a/bin/cp
+++ b/bin/cp
@@ -10,12 +10,16 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger pos dest "destination"
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -39,11 +43,16 @@ _arg_leftovers=()
 
 print_help()
 {
-	echo -e "scp:"
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "scp:"
 	echo -e "	src: source"
 	echo -e "	dest: destination"
 	echo -e "Usage :
-	$0 <src> <dest>"
+	$0 <src> <dest>";
+	fi
+
 }
 
 parse_commandline()
@@ -61,6 +70,14 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -75,7 +92,10 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="src dest"
-	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -94,7 +114,7 @@ assign_positional_args()
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
 			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -111,9 +131,20 @@ print_debug()
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
@@ -153,7 +184,7 @@ if sshm0_load_server "$_server_name"; then
   fi
 	coarg+=("$_src" "$_dest");
 
-	# echo "scp ${coarg[@]}";
+	# echo "scp ${coarg[*]}";
 
 	scp "${coarg[@]}";
 else
diff --git a/bin/edit b/bin/edit
--- a/bin/edit
+++ b/bin/edit
@@ -14,12 +14,16 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger opt port "ssh port"
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -47,7 +51,10 @@ _arg_port=
 
 print_help()
 {
-	echo -e "add a server:"
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "add a server:"
 	echo -e "	name: server name"
 	echo -e "	--ip <ip>: ip address"
 	echo -e "	--user <user>: username"
@@ -56,7 +63,9 @@ print_help()
 	echo -e "	--auth <auth>: authentication type [one of '' 'key' 'password']"
 	echo -e "	--port <port>: ssh port"
 	echo -e "Usage :
-	$0 <name> [--ip <value>] [--user <value>] [--password <value>] [--key <value>] [--auth <value>] [--port <value>]"
+	$0 <name> [--ip <value>] [--user <value>] [--password <value>] [--key <value>] [--auth <value>] [--port <value>]";
+	fi
+
 }
 
 parse_commandline()
@@ -136,6 +145,14 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -150,8 +167,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -163,7 +185,7 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -175,18 +197,29 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tip: ${_arg_ip | sed 's/-/_/g'}";
-	echo -e "\tuser: ${_arg_user | sed 's/-/_/g'}";
-	echo -e "\tpassword: ${_arg_password | sed 's/-/_/g'}";
-	echo -e "\tkey: ${_arg_key | sed 's/-/_/g'}";
-	echo -e "\tauth: ${_arg_auth | sed 's/-/_/g'}";
-	echo -e "\tport: ${_arg_port | sed 's/-/_/g'}";
+	echo -e "\tip: ${_arg_ip}";
+	echo -e "\tuser: ${_arg_user}";
+	echo -e "\tpassword: ${_arg_password}";
+	echo -e "\tkey: ${_arg_key}";
+	echo -e "\tauth: ${_arg_auth}";
+	echo -e "\tport: ${_arg_port}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/bin/plugin b/bin/plugin
--- a/bin/plugin
+++ b/bin/plugin
@@ -1,19 +1,23 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "run a plugin" --option "_help" --short-option "h"
+# @parseArger-help "run a plugin" --option "help" --short-option "h"
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
 source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger-leftovers leftovers
 # @parseArger-declarations
-# @parseArger pos plugin "plugin to execute: $(sshm0_get_plugin_list)"
+# @parseArger pos plugin "plugin to execute: "
 # @parseArger-declarations-end
+
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
 
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -36,10 +40,15 @@ _arg_leftovers=()
 
 print_help()
 {
-	echo -e "run a plugin:"
-	echo -e "	plugin: plugin to execute: $(sshm0_get_plugin_list)"
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "run a plugin:"
+	echo -e "	plugin: plugin to execute: "
 	echo -e "Usage :
-	$0 <plugin>"
+	$0 <plugin>";
+	fi
+
 }
 
 parse_commandline()
@@ -49,12 +58,20 @@ parse_commandline()
 	do
 		_key="$1"
 		case "$_key" in
-			-h|--_help)
+			-h|--help)
 				print_help;
 				exit 0;
 				;;
 			-h*)
 				print_help;
+				exit 0;
+				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
 				exit 0;
 				;;
 			*)
@@ -71,7 +88,10 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="plugin"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -90,7 +110,7 @@ assign_positional_args()
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
 			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -106,9 +126,20 @@ print_debug()
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/sshm0 b/sshm0
--- a/sshm0
+++ b/sshm0
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 # @parseArger-begin
-# @parseArger-help "sshM0: A CLI ssh manager" --option "_help" --short-option "h"
+# @parseArger-help "sshM0: A CLI ssh manager" --option "help" --short-option "h"
+# @parseArger-version "0.1" --option "version" --short-option "v"
 # @parseArger-set export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
 export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
@@ -12,12 +13,16 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger opt config-dir "directory containing the configurations" --default-value "/home/didi/.config/sshm0"
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
@@ -43,11 +48,25 @@ _arg_leftovers=()
 
 print_help()
 {
-	echo -e "sshM0: A CLI ssh manager:"
+
+	if [ "${#_positionals[@]}" -ge 1 ]; then
+		echo "$0 sub command help
+	"
+	else
+	
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "sshM0: A CLI ssh manager:"
 	echo -e "	target: what to do [one of 'list' 'add' 'edit' 'connect' 'remove' 'plugin' 'cp']"
 	echo -e "	--config-dir <config-dir>: directory containing the configurations [default: ' /home/didi/.config/sshm0 ']"
 	echo -e "Usage :
-	$0 <target> [--config-dir <value>]"
+	$0 <target> [--config-dir <value>]";
+	fi
+
+	fi
+	
+
 }
 
 parse_commandline()
@@ -66,12 +85,18 @@ parse_commandline()
 				_arg_config_dir="${_key##--config-dir=}"
 				;;
 			
-			-h|--_help)
+			-h|--help)
 				print_help;
-				exit 0;
 				;;
 			-h*)
 				print_help;
+				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
 				exit 0;
 				;;
 			*)
@@ -88,7 +113,10 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="target"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -107,7 +135,7 @@ assign_positional_args()
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
 			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -119,14 +147,25 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\ttarget: ${_arg_target}";
-	echo -e "\tconfig-dir: ${_arg_config-dir | sed 's/-/_/g'}";
+	echo -e "\tconfig-dir: ${_arg_config_dir}";
 	echo -e "\tleftovers: ${_arg_leftovers[*]}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "0.1";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
