...

diff --git a/bin/add b/bin/add
--- a/bin/add
+++ b/bin/add
@@ -17,6 +17,8 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger flag force "force overwrite if server exists" --short f
 # @parseArger flag connect "connect to server" --short c
 # @parseArger opt tag "comma-separated tags" --short t
+# @parseArger opt proxy "proxy jump server name" --short J
+# @parseArger opt timeout "connection timeout in seconds" --default-value "10"
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -63,6 +65,9 @@ _arg_port="22"
 _arg_force="off"
 _arg_connect="off"
 _arg_tag=
+_arg_group=
+_arg_proxy=
+_arg_timeout="10"
 # NESTED
 _verbose_level="0";
 
@@ -85,8 +90,11 @@ print_help()
 	echo -e "	-f|--force|--no-force: force overwrite if server exists"
 	echo -e "	-c|--connect|--no-connect: connect to server"
 	echo -e "	-t, --tag <tag>: comma-separated tags"
+	echo -e "	-J, --proxy <proxy>: proxy jump server name"
+	echo -e "	--timeout <timeout>: connection timeout in seconds [default: ' 10 ']"
+	echo -e "	-g, --group <group>: server group"
 	echo -e "Usage :
-	$0 <name> <ip> <user> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--tag <value>] [--[no-]force] [--[no-]connect]";
+	$0 <name> <ip> <user> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--tag <value>] [--group <value>] [--proxy <value>] [--timeout <value>] [--[no-]force] [--[no-]connect]";
 	fi
 
 }
@@ -198,6 +206,39 @@ parse_commandline()
 				_arg_tag="${_key##-t}"
 				;;
 			
+			--timeout)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_timeout="$2"
+				shift
+				;;
+			--timeout=*)
+				_arg_timeout="${_key##--timeout=}"
+				;;
+			
+			-g|--group)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_group="$2"
+				shift
+				;;
+			--group=*)
+				_arg_group="${_key##--group=}"
+				;;
+			-g*)
+				_arg_group="${_key##-g}"
+				;;
+			
+			-J|--proxy)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_proxy="$2"
+				shift
+				;;
+			--proxy=*)
+				_arg_proxy="${_key##--proxy=}"
+				;;
+			-J*)
+				_arg_proxy="${_key##-J}"
+				;;
+			
 			-f|--force)
 				_arg_force="on"
 				;;
@@ -296,6 +337,9 @@ print_debug()
 	echo -e "	force: ${_arg_force}";
 	echo -e "	connect: ${_arg_connect}";
 	echo -e "	tag: ${_arg_tag}";
+	echo -e "	timeout: ${_arg_timeout}";
+	echo -e "	group: ${_arg_group}";
+	echo -e "	proxy: ${_arg_proxy}";
 
 }
 
@@ -337,6 +381,8 @@ if [ -z "$_arg_name" ] && [ -z "$_arg_ip" ]; then
 	read -rp "Port [22]: " _arg_port
 	_arg_port="${_arg_port:-22}"
 	read -rp "Tags (comma-separated): " _arg_tag
+	read -rp "Group: " _arg_group
+	read -rp "Proxy server [none]: " _arg_proxy
 	echo ""
 fi
 
@@ -349,15 +395,17 @@ if [[ "${_arg_force}" == "on" ]];then
 fi
 
 if [ "$dowrite" -eq 0 ]; then
+	sshm0_validate_server "$_arg_ip" "$_arg_port" "$_arg_user" "$_arg_auth" "$_arg_key" || exit 1
 	_tmpcfg="$(mktemp)"
 	printf '# sshm0 server config\n' > "$_tmpcfg"
-	printf 'sshm0_server_ip=%s\nsshm0_server_user=%s\nsshm0_server_port=%s\nsshm0_server_auth=%s\nsshm0_server_password=%s\nsshm0_server_key=%s\nsshm0_server_cd=%s\nsshm0_server_exec_before=%s\n' \
+	printf 'sshm0_server_ip=%s\nsshm0_server_user=%s\nsshm0_server_port=%s\nsshm0_server_auth=%s\nsshm0_server_password=%s\nsshm0_server_key=%s\nsshm0_server_timeout=%s\nsshm0_server_cd=%s\nsshm0_server_exec_before=%s\n' \
 		"$(printf '%q' "$_arg_ip")" \
 		"$(printf '%q' "$_arg_user")" \
 		"$(printf '%q' "$_arg_port")" \
 		"$(printf '%q' "$_arg_auth")" \
 		"$(printf '%q' "$_arg_password")" \
 		"$(printf '%q' "$_arg_key")" \
+		"$(printf '%q' "$_arg_timeout")" \
 		"" \
 		"()" \
 		>> "$_tmpcfg" || { rm -f "$_tmpcfg"; die "Failed to write server config" 1; }
@@ -372,6 +420,8 @@ if [ "$dowrite" -eq 0 ]; then
 		done
 	fi
 	printf 'sshm0_server_tags=(%s)\n' "$_tags_value" >> "$_tmpcfg"
+	printf 'sshm0_server_group=%s\n' "$(printf '%q' "$_arg_group")" >> "$_tmpcfg"
+	printf 'sshm0_server_proxy=%s\n' "$(printf '%q' "$_arg_proxy")" >> "$_tmpcfg"
 	chmod 600 "$_tmpcfg" || { rm -f "$_tmpcfg"; die "Failed to chmod server config" 1; }
 	mv "$_tmpcfg" "$(sshm0_server_config_path "$_arg_name")" || { rm -f "$_tmpcfg"; die "Failed to save server config" 1; }
 	log "Writting to $(sshm0_server_config_path "$_arg_name")" 2;
diff --git a/bin/edit b/bin/edit
--- a/bin/edit
+++ b/bin/edit
@@ -16,6 +16,8 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger opt port "ssh port"
 # @parseArger flag connect "connect to server" --short c
 # @parseArger opt tag "comma-separated tags" --short t
+# @parseArger opt proxy "proxy jump server name" --short J
+# @parseArger opt timeout "connection timeout in seconds"
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -59,6 +61,9 @@ _arg_auth=
 _one_of_arg_auth=("" "key" "password" );
 _arg_port=
 _arg_tag=
+_arg_group=
+_arg_proxy=
+_arg_timeout=
 # FLAGS
 _arg_connect="off"
 # NESTED
@@ -82,8 +87,11 @@ print_help()
 	echo -e "	--port <port>: ssh port"
 	echo -e "	-c|--connect|--no-connect: connect to server"
 	echo -e "	-t, --tag <tag>: comma-separated tags"
+	echo -e "	-J, --proxy <proxy>: proxy jump server name"
+	echo -e "	--timeout <timeout>: connection timeout in seconds"
+	echo -e "	-g, --group <group>: server group"
 	echo -e "Usage :
-	$0 <name> [--ip <value>] [--user <value>] [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--tag <value>] [--[no-]connect]";
+	$0 <name> [--ip <value>] [--user <value>] [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--tag <value>] [--group <value>] [--proxy <value>] [--timeout <value>] [--[no-]connect]";
 	fi
 
 }
@@ -200,6 +208,39 @@ parse_commandline()
 				_arg_tag="${_key##-t}"
 				;;
 			
+			--timeout)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_timeout="$2"
+				shift
+				;;
+			--timeout=*)
+				_arg_timeout="${_key##--timeout=}"
+				;;
+			
+			-g|--group)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_group="$2"
+				shift
+				;;
+			--group=*)
+				_arg_group="${_key##--group=}"
+				;;
+			-g*)
+				_arg_group="${_key##-g}"
+				;;
+			
+			-J|--proxy)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_proxy="$2"
+				shift
+				;;
+			--proxy=*)
+				_arg_proxy="${_key##--proxy=}"
+				;;
+			-J*)
+				_arg_proxy="${_key##-J}"
+				;;
+			
 			-c|--connect)
 				_arg_connect="on"
 				;;
@@ -291,6 +332,9 @@ print_debug()
 	echo -e "	port: ${_arg_port}";
 	echo -e "	connect: ${_arg_connect}";
 	echo -e "	tag: ${_arg_tag}";
+	echo -e "	timeout: ${_arg_timeout}";
+	echo -e "	group: ${_arg_group}";
+	echo -e "	proxy: ${_arg_proxy}";
 
 }
 
@@ -320,7 +364,7 @@ trap on_interrupt INT;
 
 if sshm0_load_server "$_arg_name"; then
 #shellcheck source=../server.dist
-	if [ -z "$_arg_ip" ] && [ -z "$_arg_user" ] && [ -z "$_arg_password" ] && [ -z "$_arg_key" ] && [ -z "$_arg_auth" ] && [ -z "$_arg_port" ] && [ -z "$_arg_tag" ]; then
+	if [ -z "$_arg_ip" ] && [ -z "$_arg_user" ] && [ -z "$_arg_password" ] && [ -z "$_arg_key" ] && [ -z "$_arg_auth" ] && [ -z "$_arg_port" ] && [ -z "$_arg_tag" ] && [ -z "$_arg_group" ] && [ -z "$_arg_proxy" ]; then
 		echo "Editing server: $_arg_name (current values in brackets)"
 		read -rp "IP address [$sshm0_server_ip]: " _arg_ip
 		_arg_ip="${_arg_ip:-$sshm0_server_ip}"
@@ -339,6 +383,10 @@ if sshm0_load_server "$_arg_name"; then
 		read -rp "Tags (comma-separated) [$(IFS=,; echo "${sshm0_server_tags[*]}")]: " _arg_tag
 		_current_tags="$(IFS=,; echo "${sshm0_server_tags[*]}")"
 		_arg_tag="${_arg_tag:-$_current_tags}"
+		read -rp "Group [$sshm0_server_group]: " _arg_group
+		_arg_group="${_arg_group:-$sshm0_server_group}"
+		read -rp "Proxy server [${sshm0_server_proxy:-none}]: " _arg_proxy
+		_arg_proxy="${_arg_proxy:-$sshm0_server_proxy}"
 		echo ""
 	fi
 	if [ "$_arg_ip" != "" ]; then
@@ -349,8 +397,14 @@ if sshm0_load_server "$_arg_name"; then
 		sshm0_server_user="$_arg_user"
 	fi
 
-	edArg=("--force" "$_arg_name" "$sshm0_server_ip" "$sshm0_server_user");
+  edArg=("--force" "$_arg_name" "$sshm0_server_ip" "$sshm0_server_user");
 	
+  _final_port="${_arg_port:-$sshm0_server_port}"
+  _final_auth="${_arg_auth:-$sshm0_server_auth}"
+  _final_password="${_arg_password:-$sshm0_server_password}"
+  _final_key="${_arg_key:-$sshm0_server_key}"
+  sshm0_validate_server "$sshm0_server_ip" "$_final_port" "$sshm0_server_user" "$_final_auth" "$_final_key" || exit 1
+
 	if [ "$_arg_port" != "" ]; then
 		edArg+=("--port" "$_arg_port")
 	elif [ "$sshm0_server_port" != "" ]; then
@@ -373,6 +427,21 @@ if sshm0_load_server "$_arg_name"; then
 	fi
 	if [ "$_arg_tag" != "" ]; then
 		edArg+=("--tag" "$_arg_tag")
+	fi
+	if [ "$_arg_timeout" != "" ]; then
+		edArg+=("--timeout" "$_arg_timeout")
+	elif [ "$sshm0_server_timeout" != "" ]; then
+		edArg+=("--timeout" "$sshm0_server_timeout")
+	fi
+	if [ "$_arg_group" != "" ]; then
+		edArg+=("--group" "$_arg_group")
+	elif [ "$sshm0_server_group" != "" ]; then
+		edArg+=("--group" "$sshm0_server_group")
+	fi
+	if [ "$_arg_proxy" != "" ]; then
+		edArg+=("--proxy" "$_arg_proxy")
+	elif [ "$sshm0_server_proxy" != "" ]; then
+		edArg+=("--proxy" "$sshm0_server_proxy")
 	fi
 	if [ "$_arg_connect" != "off" ]; then
 		edArg+=("--connect")
diff --git a/bin/list b/bin/list
--- a/bin/list
+++ b/bin/list
@@ -11,6 +11,8 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger opt filter "filter by name pattern" --short f
 # @parseArger flag long "show extended info" --short l
 # @parseArger flag recent "show recently connected servers first" --short r
+# @parseArger opt group "filter by group" --short g
+# @parseArger flag tree "show servers organized by groups"
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -47,9 +49,11 @@ _optional_positionals=();
 # OPTIONALS ARGUMENTS
 _arg_tag=
 _arg_filter=
+_arg_group=
 # FLAGS
 _arg_long="off"
 _arg_recent="off"
+_arg_tree="off"
 # NESTED
 _verbose_level="0";
 
@@ -66,8 +70,10 @@ print_help()
 	echo -e "	-f, --filter <filter>: filter by name pattern"
 	echo -e "	-l|--long|--no-long: show extended info"
 	echo -e "	-r|--recent|--no-recent: show recently connected servers first"
+	echo -e "	-g, --group <group>: filter by group"
+	echo -e "	--tree|--no-tree: show servers organized by groups"
 	echo -e "Usage :
-	$0 [--tag <value>] [--filter <value>] [--[no-]long] [--[no-]recent]";
+	$0 [--tag <value>] [--filter <value>] [--group <value>] [--[no-]long] [--[no-]recent] [--[no-]tree]";
 	fi
 
 }
@@ -146,6 +152,25 @@ parse_commandline()
 			--no-long)
 				_arg_long="off"
 				;;
+			
+			-g|--group)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_group="$2"
+				shift
+				;;
+			--group=*)
+				_arg_group="${_key##--group=}"
+				;;
+			-g*)
+				_arg_group="${_key##-g}"
+				;;
+			
+			--tree)
+				_arg_tree="on"
+				;;
+			--no-tree)
+				_arg_tree="off"
+				;;
 			-h|--help)
 				print_help;
 				exit 0;
@@ -221,6 +246,9 @@ print_debug()
 	echo -e "	tag: ${_arg_tag}";
 	echo -e "	filter: ${_arg_filter}";
 	echo -e "	long: ${_arg_long}";
+	echo -e "	recent: ${_arg_recent}";
+	echo -e "	group: ${_arg_group}";
+	echo -e "	tree: ${_arg_tree}";
 
 }
 
@@ -255,6 +283,7 @@ for _server_config in "$SSHM0_CONFIG_DIR/servers/"*; do
 	sshm0_server_ip=""
 	sshm0_server_user=""
 	sshm0_server_tags=()
+	sshm0_server_group=""
 	# shellcheck source=../server.dist
 	source "$_server_config"
 
@@ -271,6 +300,10 @@ for _server_config in "$SSHM0_CONFIG_DIR/servers/"*; do
 			fi
 		done
 		[ "$_found_tag" -eq 1 ] || continue
+	fi
+
+	if [ -n "$_arg_group" ]; then
+		[ "$sshm0_server_group" = "$_arg_group" ] || continue
 	fi
 
 	_matching+=("$_name")
@@ -294,19 +327,39 @@ if [ "$_arg_recent" = "on" ]; then
 	done <<< "$_sorted"
 fi
 
-for _name in "${_matching[@]}"; do
-	if [ "$_arg_long" = "on" ]; then
-		sshm0_server_ip=""
-		sshm0_server_user=""
-		sshm0_server_tags=()
-		# shellcheck source=../server.dist
+if [ "$_arg_tree" = "on" ]; then
+	declare -A _tree_groups
+	_group_list=""
+	for _name in "${_matching[@]}"; do
+		sshm0_server_group=""
 		source "$SSHM0_CONFIG_DIR/servers/$_name"
-		_tags_str=""
-		if [ ${#sshm0_server_tags[@]} -gt 0 ]; then
-			_tags_str="$(IFS=,; echo "${sshm0_server_tags[*]}")"
+		_grp="${sshm0_server_group:-ungrouped}"
+		if [[ -z "${_tree_groups[$_grp]+x}" ]]; then
+			_tree_groups["$_grp"]=""
+			_group_list+="$_grp"$'\n'
 		fi
-		printf '%-20s %-15s %-10s [%s]\n' "$_name" "$sshm0_server_ip" "$sshm0_server_user" "$_tags_str"
-	else
-		echo "$_name"
-	fi
-done
+		_tree_groups["$_grp"]+="  $_name"$'\n'
+	done
+	while IFS= read -r _grp; do
+		[ -z "$_grp" ] && continue
+		echo "${_grp}:"
+		printf '%s' "${_tree_groups[$_grp]}"
+	done <<< "$(printf '%s' "$_group_list" | sort)"
+else
+	for _name in "${_matching[@]}"; do
+		if [ "$_arg_long" = "on" ]; then
+			sshm0_server_ip=""
+			sshm0_server_user=""
+			sshm0_server_tags=()
+			# shellcheck source=../server.dist
+			source "$SSHM0_CONFIG_DIR/servers/$_name"
+			_tags_str=""
+			if [ ${#sshm0_server_tags[@]} -gt 0 ]; then
+				_tags_str="$(IFS=,; echo "${sshm0_server_tags[*]}")"
+			fi
+			printf '%-20s %-15s %-10s [%s]\n' "$_name" "$sshm0_server_ip" "$sshm0_server_user" "$_tags_str"
+		else
+			echo "$_name"
+		fi
+	done
+fi
diff --git a/bin/utils b/bin/utils
--- a/bin/utils
+++ b/bin/utils
@@ -85,6 +85,49 @@ sshm0_load_server() {
   return 0
 }
 
+sshm0_validate_server() {
+  local _ip="$1" _port="$2" _user="$3" _auth="$4" _key="$5"
+
+  if [ -z "$_ip" ]; then
+    echo "Error: IP/hostname must not be empty" >&2
+    return 1
+  fi
+  if ! [[ "$_ip" =~ ^[a-zA-Z0-9]([a-zA-Z0-9._:-]*[a-zA-Z0-9])?$ ]]; then
+    echo "Error: invalid IP/hostname '$_ip'" >&2
+    return 1
+  fi
+
+  if [ -z "$_port" ]; then
+    echo "Error: port must not be empty" >&2
+    return 1
+  fi
+  if ! [[ "$_port" =~ ^[0-9]+$ ]] || [ "$_port" -lt 1 ] || [ "$_port" -gt 65535 ]; then
+    echo "Error: port must be numeric and between 1-65535" >&2
+    return 1
+  fi
+
+  if [ -z "$_user" ]; then
+    echo "Error: user must not be empty" >&2
+    return 1
+  fi
+
+  if [ "$_auth" = "key" ] && [ -z "$_key" ]; then
+    echo "Error: key path must be provided when auth is 'key'" >&2
+    return 1
+  fi
+
+  return 0
+}
+
+sshm0_get_proxy_args() {
+  (
+    sshm0_load_server "$1" || exit 1
+    [ -n "$sshm0_server_proxy" ] || exit 1
+    sshm0_load_server "$sshm0_server_proxy" || exit 1
+    echo "${sshm0_server_user}@${sshm0_server_ip}:${sshm0_server_port}"
+  )
+}
+
 sshm0_record_connection() {
   local _history_file="$SSHM0_CONFIG_DIR/history"
   local _timestamp
