parseArger fix

diff --git a/bin/add b/bin/add
--- a/bin/add
+++ b/bin/add
@@ -59,7 +59,7 @@ print_help()
 	echo -e "	--port <port>: ssh port [default: ' 22 ']"
 	echo -e "	-f|--force|--no-force: force overwrite if server exists"
 	echo -e "Usage :
-	$0 <ip> <user> <> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--[no-]force]"
+	$0 <name> <ip> <user> [--password <value>] [--key <value>] [--auth <value>] [--port <value>] [--[no-]force]"
 }
 
 parse_commandline()
@@ -152,7 +152,7 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
 		shift;
 	done
 }
@@ -202,5 +202,3 @@ sshm0_server_exec_before=()" > "$(sshm0_server_config_path "$_arg_name")"
 else
 	echo "$_arg_name already exists, use --force to overwrite"
 fi
-
-
