latest parseArgere

diff --git a/bin/connect b/bin/connect
--- a/bin/connect
+++ b/bin/connect
@@ -2,7 +2,8 @@
 
 # @parseArger-begin
 # @parseArger-help "connect to a server" --option "help" --short-option "h"
-# @parseArger-version "0.1.1" --option "version" --short-option "v"
+# @parseArger-version "0.2" --option "version" --short-option "v"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
 source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger-leftovers leftovers
@@ -14,6 +15,7 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 
 # @parseArger-utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
@@ -21,7 +23,7 @@ die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo -e "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -42,10 +44,13 @@ _arg_exec_before=()
 # FLAGS
 # LEFTOVERS
 _arg_leftovers=()
+_verbose_level="0";
+
 
 
 print_help()
 {
+	_triggerSCHelp=1;
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
@@ -57,6 +62,37 @@ print_help()
 	$0 <name> [--cd <value>] [--exec-before <value>]";
 	fi
 
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -100,6 +136,15 @@ parse_commandline()
 				print_version;
 				exit 0;
 				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -134,9 +179,9 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
-			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -156,7 +201,7 @@ print_debug()
 
 print_version()
 {
-	echo "0.1.1";
+	echo "0.2";
 }
 
 on_interrupt() {
@@ -169,6 +214,7 @@ assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
 
 
+
 # @parseArger-parsing-end
 # print_debug "$@"
 # @parseArger-end
@@ -177,25 +223,38 @@ trap on_interrupt INT;
 
 if sshm0_load_server "$_arg_name"; then
   coarg=("${sshm0_server_user}@${sshm0_server_ip}" "-p" "${sshm0_server_port}");
+	
+	log "Connecting to $_arg_name :
+	${sshm0_server_user}@${sshm0_server_ip}:${sshm0_server_port}" 2;
 
   if [ "$sshm0_server_auth" == "key" ]; then
+		log "Using auth key
+	$sshm0_server_key" 2;
+
     coarg+=("-i" "$sshm0_server_key");
   fi
 
 	ecmd="";
   if [ "$_arg_cd" != "" ] || [ "$sshm0_server_cd" != "" ] || [ "${#_arg_exec_before[@]}" -gt 0 ]; then
 		if [ "$_arg_cd" != "" ]; then
+			log "Remote directory :
+	$_arg_cd" 2;
+
 			ecmd+="cd $_arg_cd;";
 		elif [ "$sshm0_server_cd" != "" ]; then
 			ecmd+="cd $sshm0_server_cd;";
 		fi
 
 		if [ "${#_arg_exec_before[@]}" -gt 0 ]; then
+			log "Executing before :" 2;
 			for ebefore in "${_arg_exec_before[@]}"; do
+				log "	$ebefore" 2;
 				ecmd+="$ebefore;";
 			done
 		elif [ "${#sshm0_server_exec_before[@]}" -gt 0 ]; then
+			log "Executing before :" 2;
 			for ebefore in "${sshm0_server_exec_before[@]}"; do
+				log "	$ebefore" 2;
 				ecmd+="$ebefore;";
 			done
 		fi
diff --git a/bin/plugin b/bin/plugin
--- a/bin/plugin
+++ b/bin/plugin
@@ -1,7 +1,8 @@
 #!/bin/bash
 # @parseArger-begin
 # @parseArger-help "run a plugin" --option "help" --short-option "h"
-# @parseArger-version "0.1.1" --option "version" --short-option "v"
+# @parseArger-version "0.2" --option "version" --short-option "v"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
 source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger-leftovers leftovers
@@ -11,6 +12,7 @@ source "$SSHM0_ROOT_DIR/bin/utils";
 
 # @parseArger-utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
@@ -18,7 +20,7 @@ die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo -e "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -37,10 +39,13 @@ _arg_plugin="";
 # FLAGS
 # LEFTOVERS
 _arg_leftovers=()
+_verbose_level="0";
+
 
 
 print_help()
 {
+	_triggerSCHelp=1;
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
@@ -50,6 +55,37 @@ print_help()
 	$0 <plugin>";
 	fi
 
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -75,6 +111,15 @@ parse_commandline()
 				print_version;
 				exit 0;
 				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -109,9 +154,9 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
-			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -129,7 +174,7 @@ print_debug()
 
 print_version()
 {
-	echo "0.1.1";
+	echo "0.2";
 }
 
 on_interrupt() {
@@ -140,6 +185,7 @@ parse_commandline "$@";
 handle_passed_args_count;
 assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
+
 
 
 # @parseArger-parsing-end
diff --git a/sshm0 b/sshm0
--- a/sshm0
+++ b/sshm0
@@ -2,19 +2,21 @@
 
 # @parseArger-begin
 # @parseArger-help "sshM0: A CLI ssh manager" --option "help" --short-option "h"
-# @parseArger-version "0.1.1" --option "version" --short-option "v"
+# @parseArger-version "0.2" --option "version" --short-option "v"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-set export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
 export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
 source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger-leftovers leftovers
 # @parseArger-declarations
-# @parseArger pos target "what to do" --subcommand --one-of "list" --one-of "add" --one-of "edit" --one-of "connect" --one-of "remove" --one-of "plugin" --one-of "cp"
+# @parseArger pos target "what to do" --subcommand-directory "bin" --subcommand-use-leftovers --subcommand --one-of "list" --one-of "add" --one-of "edit" --one-of "connect" --one-of "remove" --one-of "plugin" --one-of "cp" --one-of "cp"
 # @parseArger opt config-dir "directory containing the configurations" --default-value "/home/didi/.config/sshm0"
 # @parseArger-declarations-end
 
 # @parseArger-utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
@@ -22,7 +24,7 @@ die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo -e "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -37,28 +39,33 @@ begins_with_short_option()
 # POSITIONALS ARGUMENTS
 _positionals=();
 _arg_target="";
-_one_of_arg_target=("list" "add" "edit" "connect" "remove" "plugin" "cp" );
+_one_of_arg_target=("list" "add" "edit" "connect" "remove" "plugin" "cp" "cp" );
 _arg_subcommand_arg="_arg_target";
+__subcommand=();
 # OPTIONALS ARGUMENTS
 _arg_config_dir="/home/didi/.config/sshm0"
 # FLAGS
 # LEFTOVERS
 _arg_leftovers=()
+_verbose_level="0";
+
 
 
 print_help()
 {
+	_triggerSCHelp=1;
 
 	if [ "${#_positionals[@]}" -ge 1 ]; then
 		echo "$0 sub command help
 	"
+		_triggerSCHelp=0;
 	else
 	
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
 		echo -e "sshM0: A CLI ssh manager:"
-	echo -e "	target: what to do [one of 'list' 'add' 'edit' 'connect' 'remove' 'plugin' 'cp']"
+	echo -e "	target: what to do [one of 'list' 'add' 'edit' 'connect' 'remove' 'plugin' 'cp' 'cp']"
 	echo -e "	--config-dir <config-dir>: directory containing the configurations [default: ' /home/didi/.config/sshm0 ']"
 	echo -e "Usage :
 	$0 <target> [--config-dir <value>]";
@@ -67,6 +74,37 @@ print_help()
 	fi
 	
 
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -99,6 +137,15 @@ parse_commandline()
 				print_version;
 				exit 0;
 				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -133,9 +180,10 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
-			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+			__subcommand+=("$_SCRIPT_DIR/bin/${1}");
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -154,7 +202,7 @@ print_debug()
 
 print_version()
 {
-	echo "0.1.1";
+	echo "0.2";
 }
 
 on_interrupt() {
@@ -166,6 +214,11 @@ handle_passed_args_count;
 assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
 
+
+if [ "$_triggerSCHelp" == "0" ];then
+	__subcommand+=("--help");
+fi
+__subcommand+=("${_arg_leftovers[@]}");
 
 # @parseArger-parsing-end
 # print_debug "$@"
@@ -180,4 +233,7 @@ fi
 # shellcheck source=config.dist
 source "$SSHM0_CONFIG_DIR/config";
 
-"$SSHM0_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}";
+log "subcommand :" 3;
+log "\t\t${__subcommand[*]}" 3;
+
+"${__subcommand[@]}";
