plugins

diff --git a/bin/plugin b/bin/plugin
--- a/bin/plugin
+++ b/bin/plugin
@@ -1,15 +1,11 @@
 #!/bin/bash
-
 # @parseArger-begin
-# @parseArger-help "sshM0: A CLI ssh manager" --option "_help" --short-option "h"
-# @parseArger-set export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
-export SSHM0_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
+# @parseArger-help "run a plugin" --option "_help" --short-option "h"
 # @parseArger-source $SSHM0_ROOT_DIR/bin/utils
 source "$SSHM0_ROOT_DIR/bin/utils";
 # @parseArger-leftovers leftovers
 # @parseArger-declarations
-# @parseArger pos target "what to do" --subcommand --one-of "list" --one-of "add" --one-of "edit" --one-of "connect" --one-of "remove" --one-of "plugin"
-# @parseArger opt config-dir "directory containing the configurations" --default-value "$HOME/.config/sshm0"
+# @parseArger pos plugin "plugin to execute: $(sshm0_get_plugin_list)"
 # @parseArger-declarations-end
 
 # @parseArger-parsing
@@ -31,11 +27,8 @@ begins_with_short_option()
 
 # POSITIONALS ARGUMENTS
 _positionals=();
-_arg_target="";
-_one_of_arg_target=("list" "add" "edit" "connect" "remove" "plugin" );
-_arg_subcommand_arg="_arg_target";
+_arg_plugin="";
 # OPTIONALS ARGUMENTS
-_arg_config_dir="$HOME/.config/sshm0"
 # FLAGS
 # LEFTOVERS
 _arg_leftovers=()
@@ -43,11 +36,10 @@ _arg_leftovers=()
 
 print_help()
 {
-	echo -e "sshM0: A CLI ssh manager:"
-	echo -e "	target: what to do [one of 'list' 'add' 'edit' 'connect' 'remove' 'plugin']"
-	echo -e "	--config-dir <config-dir>: directory containing the configurations [default: ' $HOME/.config/sshm0 ']"
+	echo -e "run a plugin:"
+	echo -e "	plugin: plugin to execute: $(sshm0_get_plugin_list)"
 	echo -e "Usage :
-	$0 <target> [--config-dir <value>]"
+	$0 <plugin>"
 }
 
 parse_commandline()
@@ -57,15 +49,6 @@ parse_commandline()
 	do
 		_key="$1"
 		case "$_key" in
-			--config-dir)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_config_dir="$2"
-				shift
-				;;
-			--config-dir=*)
-				_arg_config_dir="${_key##--config-dir=}"
-				;;
-			
 			-h|--_help)
 				print_help;
 				exit 0;
@@ -87,7 +70,7 @@ parse_commandline()
 
 handle_passed_args_count()
 {
-	local _required_args_string="target"
+	local _required_args_string="plugin"
 	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
 }
 
@@ -95,7 +78,7 @@ handle_passed_args_count()
 assign_positional_args()
 {
 	local _positional_name _shift_for=$1;
-	_positional_names="_arg_target ";
+	_positional_names="_arg_plugin ";
 	_leftovers_count=$((${#_positionals[@]} - 1))
 	for ((ii = 0; ii < _leftovers_count; ii++));do
 		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]";
@@ -118,8 +101,7 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "\ttarget: ${_arg_target}";
-	echo -e "\tconfig-dir: ${_arg_config-dir | sed 's/-/_/g'}";
+	echo -e "\tplugin: ${_arg_plugin}";
 	echo -e "\tleftovers: ${_arg_leftovers[*]}";
 
 }
@@ -132,13 +114,13 @@ assign_positional_args 1 "${_positionals[@]}"
 # print_debug "$@"
 # @parseArger-end
 
-export SSHM0_CONFIG_DIR="$_arg_config_dir";
-
-if [ ! -d "$SSHM0_CONFIG_DIR" ]; then
-	sshm0_install;
+if plugin="$(sshm0_get_plugin "${_arg_plugin}")"; then
+	if [ -f "$plugin" ] || command -v "$(echo "$plugin" | head -n1 | cut -d " " -f1)" > /dev/null; then
+		"$plugin" "${_arg_leftovers[@]}";
+	fi
+	exit $?;
+else
+	echo "plugin $_arg_plugin not found, available plugins:";
+	sshm0_get_plugin_list "\t";
+	exit 1;
 fi
-
-# shellcheck source=config.dist
-source "$SSHM0_CONFIG_DIR/config";
-
-"$SSHM0_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}";
